require "active_support/concern"

module SchemaOrg
  module Mixins
    module Service
      extend ActiveSupport::Concern

      include Intangible

      included do
        option :aggregate_rating, optional: true # The overall rating, based on a collection of reviews or ratings, of the item.
        option :available_channel, optional: true # A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).
        option :brand, optional: true # The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
        option :category, optional: true # A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
        option :has_offer_catalog, optional: true # Indicates an OfferCatalog listing for this Organization, Person, or Service.
        option :hours_available, optional: true # The hours during which this service or contact is available.
        option :is_related_to, optional: true # A pointer to another, somehow related product (or multiple products).
        option :is_similar_to, optional: true # A pointer to another, functionally similar product (or multiple products).
        option :logo, optional: true # An associated logo.
        option :produces, optional: true # The tangible thing generated by the service, e.g. a passport, permit, etc. Superseded by `service_output`.
        option :provider_mobility, optional: true # Indicates the mobility of a provided service (e.g. 'static', 'dynamic').
        option :service_audience, optional: true # The audience eligible for this service. Superseded by `audience`.
        option :service_type, optional: true # The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
        option :slogan, optional: true # A slogan or motto associated with the item.
        option :audience, optional: true # An intended audience, i.e. a group for whom something was created. Supersedes `service_audience`.
        option :award, optional: true # An award won by or for this item. Supersedes `awards`.
        option :broker, optional: true # An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred. Supersedes `booking_agent`.
        option :offers, optional: true # An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use [[businessFunction]] to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a [[Demand]]. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer. Inverse-property: `item_offered`.
        option :provider, optional: true # The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller. Supersedes `carrier`.
        option :review, optional: true # A review of the item. Supersedes `reviews`.
        option :service_area, optional: true # The geographic area where the service is provided. Supersedes `area`. Superseded by `area_served`.
        option :service_output, optional: true # The tangible thing generated by the service, e.g. a passport, permit, etc. Supersedes `produces`.
        option :area_served, optional: true # The geographic area where a service or offered item is provided. Supersedes `service_area`.
      end
    end
  end
end
